---
title: "modeling"
author: 
  - William K Davis III
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache = TRUE
  )
library(readr)
library(dplyr)
library(tsibble)
library(fabletools)
library(feasts)
library(ggplot2)
library(lubridate)
library(caret)
library(gridExtra)
library(corrplot)
library(tidyr)
library(GGally)
library(fable)
library(fable.prophet)
```

```{r data-prep}
bikets <- readr::read_csv("SeoulBikeData.csv",
                        col_names = c("Date",
                                      "BikeCount",
                                      "Hour",
                                      "Temperature",
                                      "Humidity",
                                      "WindSpeed",
                                      "Visibility",
                                      "Dewpoint",
                                      "SolarRadiation",
                                      "Rainfall",
                                      "Snowfall",
                                      "Seasons",
                                      "Holiday",
                                      "FunctionalDay"),
                        skip = 1,
                        col_types = cols("Hour" = col_time(format = "%H"),
                                         Seasons = "f",
                                         Holiday = "f",
                                         FunctionalDay = "f")) %>%
  mutate(
    Hour = parse_date_time(
      paste(Date, Hour),
      orders = c("dmy HMS", "dmY HMS"),
      tz = "Asia/Seoul"
    ),
    .before = everything(),
    Date = NULL,
    BikeCount = ifelse(FunctionalDay == "Yes", BikeCount, NA),
    FunctionalDay = NULL,
    Holiday = forcats::fct_relevel(Holiday, "No Holiday")
  ) %>%
  as_tsibble(index = Hour)

holidays <- bikets %>%
  filter(Holiday == "Holiday") %>%
  mutate(ds = as.Date(Hour)) %>%
  distinct(ds) %>%
  mutate(holiday = "holiday")

ndays <- nrow(bikets)/24
days_for_cv <- 50

bikes_train <- stretch_tsibble(bikets,
                               .step = 24,
                               .init = nrow(bikets)-(days_for_cv*24)-3,
                               .id = "fold") %>%
  filter(fold <= 50)

bikes_test <- new_data(bikes_train, n = 27) %>%
  inner_join(bikets, by = "Hour")
```

### time-series regression

### regression with ARIMA errors

```{r arima}
future::plan(strategy = "multisession")

l <- bikets %>%
  features(BikeCount, features = guerrero) %>%
  pull(lambda_guerrero)
fourier(period = 24, K = 10) + fourier(period = 24*7, K = 5)

bikets %>%
  gg_tsdisplay(difference(box_cox(BikeCount, l), 24) %>% difference(), 
               plot_type = "partial", lag_max = 48)

## manual pdq
bikearima <- bikets %>%
  mutate(BikeCount = na_if(BikeCount, 0)) %>%
  model( arimaACF = ARIMA(box_cox(BikeCount, l) ~ 0 + PDQ(0, 1, 1) + pdq(0, 1, 11)),
         arimaPACF = ARIMA(box_cox(BikeCount, l) ~ 0 + PDQ(0, 1, 1) + pdq(9, 1, 0)))
gg_tsresiduals(bikearima)
gg_tsresiduals(bikearima, type = "response")

## auto ARIMA
bikearima <- bikets %>%
  mutate(BikeCount = na_if(BikeCount, 0)) %>%
  model(
    arima = ARIMA(box_cox(BikeCount, l) ~ PDQ(P=0:7, Q=0:7, period = "day") + PDQ(period = "week") + pdq(p = 0:12, q = 0:12)  +Dewpoint + Humidity + Rainfall + SolarRadiation + Temperature + Visibility + WindSpeed + Seasons + Holiday, stepwise = FALSE, approximation = FALSE, unitroot_spec = unitroot_options(
  ndiffs_alpha = 0.05,
  nsdiffs_alpha = 0.05,
  ndiffs_pvalue = ~feasts::unitroot_kpss(., lags = "long")["kpss_pvalue"],
  nsdiffs_pvalue = fable:::ur_seasonal_strength(0.64)
)))
gg_tsresiduals(bikearima)
gg_tsresiduals(bikearima, type = "response")

bikets_int <- interpolate(bikearima, bikets) %>%
  inner_join(select(bikets, -BikeCount), by = "Hour")
```

### Facebook Prophet

```{r model}
prophet_fit <- bikets_int %>%
  mutate(BikeCountL1 = lag(log(BikeCount), k = 1),
         BikeCountL2 = lag(log(BikeCount), k = 2),
         BikeCountL12 = lag(log(BikeCount), k = 12),
         BikeCountL24 = lag(log(BikeCount), k = 24)) %>%
  filter_index("2017-12-02 00:00:00" ~ .) %>%
  model(
    prophet = prophet(
      log(BikeCount) ~ season(
        period = "day",
        type = "additive",
        order = 10,
        name = "daily"
      ) + season(
        period = "week",
        type = "additive",
        order = 5,
        name = "weekly"
      ) + holiday(holidays = holidays) + Dewpoint + Humidity + Rainfall + SolarRadiation + Temperature + Visibility + WindSpeed)
  )
gg_tsresiduals(prophet_fit)
residuals(prophet_fit) %>%
  features(.resid, c(unitroot_kpss, unitroot_pp, ljung_box))
accuracy(prophet_fit)
tidy(prophet_fit)
```

### NNETAR

```{r nnetar}
fits <- bikets_int %>%
  mutate(BikeCount = na_if(BikeCount, 0)) %>%
  model(
    nnetar = NNETAR(box_cox(BikeCount, l) ~ AR(period = "day", ) + AR(period = "week") + Holiday + Dewpoint + Humidity + Rainfall + SolarRadiation + Temperature + Visibility + WindSpeed)) %>%
gg_tsresiduals()
```

### fasster

```{r fasster}
library(fasster)
bikets_wd <- bikets %>%
  mutate(BikeCount = na_if(BikeCount, 0),
         WorkDay = as.numeric(format(Hour, "%u")) <= 5 & Holiday == "No Holiday")
bikets_wd[8256:8760,] %>%
  select(BikeCount, WorkDay) %>%
  pivot_longer(cols = -c(BikeCount, Hour), names_to = "Day Type") %>%
  autoplot(.vars = BikeCount)
bikefasster <-  %>%
  model()
gg_tsresiduals(box_cox(BikeCount, l) ~ )
```

https://fasster.tidyverts.org
